### ISSUE TITLE
Restarts save from simulation elapsed time

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#667]
Rather than just having coarsest timestamps to check to see if restart files should be written, it would be good to also include a mechanism to have timestamps which are from when the simulation started, such that restart files would be made after X hours and/or minutes

**Comment by PhilipDeegan** [comment]
I would guess the only check that is really feasible is if the elapsed time and the next restart time are the same, only make one, but don't attempt to do anything smart like checking if there was a recent restart written if the elapsed time is triggered?

**Comment by nicolasaunai** [comment]
Not sure I understand you last comment/question. IMO the "elapsed time" is a mode of operation for the checkpointing. If selected, the code dumps a restart file every XX "real time units", rather than every "simulated time units".
So actually, what we could do is ask the user the checkpointing time interval in one variable, and the unit (real time VS simulated time) in another?

**Comment by PhilipDeegan** [comment]
is it feasible to give input parameters for both "modes" such that they can both be active?
in that case, they could possibly try to write restart files at the same timestep

**Comment by nicolasaunai** [comment]
I see now. I had not imagined they could be both actives at once. I agree that (although probably quite unfortunate) they could dump at the same time, in which case we'd want only one. I don't think in that case we can do something with the "next" dump times, because if you know when you're going to dump in the "sim unit" mode, you can't really know how when in terms of sim units the next real time dump will occur. 
I think in case both modes are active, the sim unit must be prioritized and the time at which it was done must be kept in memory so that next real time based dump checks if last "sim unit" dump has been done "recently", in which case that next real time dump is skipped?
